[package]
name = "clmm-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "3.0.0"
thiserror = "1.0"
uint = { version = "0.9.5", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
